export const GET_USER = 'GET_USER';
export const GET_INVITES = 'GET_INVITES';
export const ADD_INVITES = 'ADD_INVITES';
export const DELETE_INVITES = 'DELETE_INVITES';
export const FAILED_OPERATION = 'FAILED_OPERATION';